BaseUrl= "http://www.markgustetic.com/"
LanguageCode= "en-us"
Title= "Mark Gustetic"
paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme = "casper"

[params]
  description = "a tech, life, and philosophy blog"
  cover = "images/cover7.png"
  author = "Mark Gustetic"
  authorlocation = "Cleveland, Ohio"
  authorwebsite = "http://www.markgustetic.com"
  bio = ""
  logo = "images/logo.png"
  profile = "images/profile.jpeg"
  googleAnalyticsUserID = "UA-77198808-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "markgustetic"
  twitterName = "markgustetic"
  hideHUGOSupport = true

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "home"
  url = "/"
